### ISSUE TITLE
Go-config causing annoying suggestion box on comma

### ISSUE THREAD

**Issue by pobri19** [joefitzgerald/go-config#16]
Every time I type a comma in my go files, no matter where I am in the file or what I'm typing it after it gives this annoying suggestion window: http://imgur.com/7AeK7c0

I don't recall it always doing this, but regardless it's very frustrating. Is there any way to disable this?

Other packages I have installed (if there's some sort of weird conflict):

autocomplete-go
go-config
go-get
go-plus
environment
git-plus
jsformat
linter

If I disable go-config the problem goes away.

It would be okay if it was doing it in places that made sense, but it's unfortunately that's not the case.

Thanks :)

**Comment by joefitzgerald** [comment]
This is not a go-config issue; its autocomplete-go, or go-plus.

**Comment by pobri19** [comment]
Ah, you're right, it's an autocomplete-go problem. I'll close this and create an issue over there. Thanks.
