### ISSUE TITLE
Go-config loads environment only on start (atom < 1.7.0)

### ISSUE THREAD

**Issue by ankalus** [joefitzgerald/go-config#27]
When I change `process.env`, environments don't apply to go-config. I created package [atom-env-for-project](https://atom.io/packages/atom-env-for-project) that changes "process.env" and it doesn't work with go-config package.
Only when atom is <1.7.0 go-config don't read from `process.env` ([lib/main.js](https://github.com/joefitzgerald/go-config/blob/master/lib/main.js#L76-L86)).
What is purpose of that?

**Comment by joefitzgerald** [comment]
See: https://github.com/atom/atom/pull/11054 and https://github.com/atom/atom/pull/11337.

**Comment by ankalus** [comment]
Thanks for explanation
