### ISSUE TITLE
Cursor behaviour on save

### ISSUE THREAD

**Issue by hasit** [joefitzgerald/go-config#28]
I recently noticed that the cursor behaves a bit unexpectedly on saving the file. I know that ```gofmt``` is responsible for running ```go-imports``` when I save a file. I have recorded a GIF for this issue to provide more context.

![cursor-behaviour](http://g.recordit.co/97JqKMprvD.gif)

Issue:
On save, the cursor moves to the end of struct.

Expected behaviour:
On save, the cursor should remain at the same place.

**Comment by joefitzgerald** [comment]
Have you updated atom to the latest version, and also all packages? This was an issue, but has been fixed, I think.

**Comment by hasit** [comment]
@joefitzgerald, yes I have updated Atom and all packages. I am willing to help in any way I can, if it hasn't been fixed yet.

**Comment by joefitzgerald** [comment]
Are you open to a screen sharing session to figure this out? If so, please join the `#go-plus` channel in one of these Slack teams, and then direct message me your email address:

[![Slack](https://img.shields.io/badge/atom_slack-%23go--plus-blue.svg?style=flat)](https://atom-slack.herokuapp.com) [![Slack](https://img.shields.io/badge/gophers_slack-%23go--plus-blue.svg?style=flat)](https://gophersinvite.herokuapp.com)

**Comment by hasit** [comment]
I'd be happy to. When would be a good time to do pair on this issue?

**Comment by joefitzgerald** [comment]
So @hasit and I paired on this, we found the issue, and I resolved it in the most recent version of `gofmt`.

**Comment by hasit** [comment]
Thank you, @joefitzgerald
