### ISSUE TITLE
go-config claims that GOPATH isn't set

### ISSUE THREAD

**Issue by simon-void** [joefitzgerald/go-config#39]
As you can see, on starting Atom i get to see (after Atom autocomplete-go wants to `go get -u github.com/nsf/gocode`) an error message claiming the GOPATH isn't set. As you can also see the console output claims otherwise:
![atom-gopath](https://cloud.githubusercontent.com/assets/8070979/15343109/8f5d8e2c-1c9a-11e6-92ef-84e5c23c032e.png)
- GOROOT and GOPATH are set in my .bashrc-file
- restarting my Kubuntu 16.04 didn't solve the issue (by then the .bashrc is definetly sourced)
- i installed ATOM 1.7.3 from the deb-file provided on [atom.io](https://atom.io/)
- go-config version 1.1.4
- autocomplete-go version 1.1.0

executing `go get -u github.com/nsf/gocode` in the console worked fine but without a GOPATH Atom doesn't find it.

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955

**Comment by simon-void** [comment]
that "fixed" it (as long as i don't want to change the GOPATH for different projects i assume, at which point things would get messy)

**Comment by migueleliasweb** [comment]
@joefitzgerald What @simon-void said is true. Only using one $GOPATH and $GOROOT for every project is too messy. Should just both GOPATH and GOROOT be overwritten by a per-project configuration ?

**Comment by joefitzgerald** [comment]
Launch atom from the terminal to have per-project GOPATHs. `GOPATH=/some/path atom somedir` and `GOPATH=/some/otherpath atom someotherdir` will yield two atom Windows with different GOPATHs.

**Comment by simon-void** [comment]
hmm, that's extremely easy to overlook/forget :o 
Personally i use command-line programs from the command-line but everything with an ui i start by clicking on an icon (and having different atom icons for different projects isn't nice either).
So i'd prefer a per-project configuration in the ui as well, but does atom even have a project configuration?? I can add new project-folders, but i don't see project-specific option when i right-click on it.
But if there is per-project config (and therefore the atom could switch the context/path depending on which file and therefor project i look at), it would be nice to have a default config/path and if i want a different path for a project i'd have to specify that.
But again, i'm not 100% sure atom allows that (as a lightweight editor and not being an ide).

**Comment by migueleliasweb** [comment]
I'm not sure Atom supports per-project configurations but I also think it is doable via some plugins (eg. go-config could read a certain file on project's root folder to search for paths but i'm sure that's out-of-reach ATM). What I did was adding a script to call atom (inside the projects root folder) with needed arguments and env vars. Kinds hacky but it works...

**Comment by joefitzgerald** [comment]
You're right @migueleliasweb that Atom does not support a per-project configuration API, [yet](https://github.com/atom/atom/issues/5168). In the interim, you can use [project-manager](https://atom.io/packages/project-manager), a third party package which provides this functionality.

I do also plan to add support for project-level config in advance of Atom providing the functionality: https://github.com/joefitzgerald/go-config/issues/3

**Comment by migueleliasweb** [comment]
Hey @joefitzgerald , the idea of #3 is awesome. I don'y know if I can help in any way (since i'm not an expert in Go, neither in nodejs with Atom API) but I definitely would like to.

**Comment by migueleliasweb** [comment]
https://github.com/atom/atom/pull/11436
