### ISSUE TITLE
gopath is not set

### ISSUE THREAD

**Issue by torfuzx** [joefitzgerald/go-config#40]
Hi
My OS is Fedora 23 and Atom's version is  1.7.2.
Go-config  can not correctly identify GOPATH path.
Atom always tip me gopath is not set.
How can I solve this problem?

**Comment by torfuzx** [comment]
I make sure GOROOT and GOPATH are set in my .bashrc-file

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955

**Comment by torfuzx** [comment]
thank you.I set GOPATH in both ~/.bash_profile and ~/.bashrc.
