### ISSUE TITLE
Wrong/old GOPATH used by gometalinter(?)

### ISSUE THREAD

**Issue by jbreitbart** [joefitzgerald/go-config#48]
I am setting GOPATH and PATH in both my .profile and .bashrc as follows:
```
export GOPATH=$HOME/workspace/go_Darwin
PATH=/usr/local/go/bin:$PATH:$GOPATH/bin/
```
Furthermore I am explicitly setting GOPATH in the go-config settings to the same path, but I get the following error when I run "update and install linter" of the go-plus package: 
<img width="462" alt="bildschirmfoto 2016-07-16 um 19 12 20" src="https://cloud.githubusercontent.com/assets/881727/16896084/53797ee8-4b89-11e6-9ea6-ee86fe9784a6.png">

The path shown is the one I use at my linux system and I used the sync-setting atom package to transfer my settings from a Linux system to an OS X one, so it looks like an old PATH is stuck somewhere in the config. However, I could not find an entry of the old path in the configuration. Any idea? Or should I just reinstall my atom?

**Comment by joefitzgerald** [comment]
Check your package settings for `go-config` and `go-plus`. Blank out the GOPATH setting in each, and use the environment to set your GOPATH instead.

**Comment by jbreitbart** [comment]
I have blanked the setting in go-config, but I could not find any option in go-plus. This did not fix the error, however I manage to fix it myself.

The issue was that my old Linux $GOPATH is present on the OS X system and its bin directory somehow endet up in my $PATH (stupid c&p mistake in my .bashrc). For whatever reason, go-config decided to that this old $GOPATH with the linux binaries should be my $GOPATH and not the value I have set $GOPATH to in .profile/.bashrc.

I'll close this issue. I guess that is really a strange special case. Feel free to reopen the issue if you think it should be fixed in go-config.

**Comment by joefitzgerald** [comment]
go-config simply works with the environment you give it. If the environment is funky (sounds like you found out why) then your mileage will vary by the amount of funkiness. Glad you got it sorted out!
