### ISSUE TITLE
What about fish shell?

### ISSUE THREAD

**Issue by idoo** [joefitzgerald/go-config#55]
Thank you for this package.
Does it work with fish shell?

**Comment by joefitzgerald** [comment]
It should, provided you are running the latest atom version.

https://github.com/atom/atom/commit/bb40f843404980fed75bd849e3cdfa9def392c67

**Comment by joefitzgerald** [comment]
What operating system are you using?

**Comment by joefitzgerald** [comment]
FYI, https://github.com/atom/atom/pull/12396

**Comment by idoo** [comment]
@joefitzgerald mac and homebrew installed fish.

thank you for reference

**Comment by joefitzgerald** [comment]
@idoo it won't work until a new Atom patch release is issued that is >= 1.9.9. In the meantime, please launch from the terminal as a workaround.

**Comment by joefitzgerald** [comment]
Atom >= 1.9.9 is out, please upgrade.
