### ISSUE TITLE
Release Practices

### ISSUE THREAD

**Issue by philoserf** [joefitzgerald/go-config#59]
I encourage you to include the CHANGELOG and optimally GitHub release notes in the release process. The CHANGELOG points at the Release notes however were last updated at 1.2. There is nothing for 1.2.x

I came by looking for what is new in the latest and; while it is easy enough for someone familiar with GitHub and git, understanding what's new may be beyond the skill of some plugin users.

**Comment by joefitzgerald** [comment]
Fixed.
