### ISSUE TITLE
Background code highlight 

### ISSUE THREAD

**Issue by prvst** [joefitzgerald/go-config#64]
After some time away from my code, I opened Atom, updated all packages and now I have this all over my code:

![screenshot from 2016-11-29 15-01-23](https://cloud.githubusercontent.com/assets/403705/20726843/30c90fe0-b645-11e6-8c73-724ecbd88683.png)
 
It look random to me, there is no explanation on why some parts are highlighted like that. It took me some time to track that, and I can only remove the effect when I disable go-config. Now, I still don't know which program is doing that, but I would really love some help if you could tell me why is that happening and how to turn off that annoying "feature"

I'm running Atom 1.9.9, on an Ubuntu 16.04.1 machine.

Thanks.

**Comment by lloiser** [comment]
see https://github.com/joefitzgerald/go-plus/issues/502

**Comment by prvst** [comment]
Thanks.
